# Generated by Django 5.2.8 on 2025-12-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_portaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='login',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
