# Generated by Django 5.2.8 on 2025-12-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_portaluser_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='price_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
