# Generated by Django 5.2.8 on 2025-12-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_favoriteitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteitem',
            name='description',
        ),
    ]
