# Generated by Django 5.2.8 on 2025-12-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_productphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPrazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_code', models.CharField(db_index=True, max_length=100)),
                ('grupo_desc', models.CharField(db_index=True, max_length=100)),
                ('prazo', models.IntegerField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
