# Generated by Django 5.2.8 on 2025-12-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_grupoprazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(db_index=True, max_length=150)),
                ('product', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='product_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
        migrations.AlterField(
            model_name='grupoprazo',
            name='grupo_code',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
