# Generated by Django 5.2.4 on 2026-01-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_familyphoto_delete_productphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoInnovaro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Código')),
                ('chave', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Chave')),
                ('nome', models.TextField(verbose_name='Nome')),
                ('modelo', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Modelo')),
                ('classe', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Classe')),
                ('desc_generica', models.CharField(blank=True, max_length=150, verbose_name='Descrição Genérica')),
                ('tamanho', models.CharField(blank=True, max_length=50, verbose_name='Tamanho')),
                ('capacidade', models.CharField(blank=True, max_length=50, verbose_name='Capacidade')),
                ('rodado', models.CharField(blank=True, max_length=50, verbose_name='Rodado')),
                ('mola_freio', models.CharField(blank=True, max_length=50, verbose_name='Mola/Freio')),
                ('eixo', models.CharField(blank=True, max_length=50, verbose_name='Eixo')),
                ('pneu', models.CharField(blank=True, max_length=50, verbose_name='Pneu')),
                ('cor', models.CharField(blank=True, max_length=50, verbose_name='Cor')),
                ('funcionalidade', models.CharField(blank=True, max_length=150, verbose_name='Funcionalidade')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('crm', models.BooleanField(db_index=True, default=False, verbose_name='CRM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto Innovaro',
                'verbose_name_plural': 'Produtos Innovaro',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo', 'crm'], name='sales_produ_codigo_fb63d0_idx'), models.Index(fields=['modelo', 'crm'], name='sales_produ_modelo_f64bbd_idx')],
            },
        ),
    ]
