# Generated by Django 5.2.4 on 2026-01-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_produtoinnovaro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela_codigo', models.CharField(db_index=True, max_length=100, verbose_name='Código da Tabela')),
                ('tabela_nome', models.CharField(max_length=255, verbose_name='Nome da Tabela')),
                ('produto', models.CharField(db_index=True, max_length=255, verbose_name='Produto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Preço de Produto',
                'verbose_name_plural': 'Preços de Produtos',
                'ordering': ['tabela_nome', 'produto'],
                'indexes': [models.Index(fields=['tabela_codigo', 'produto'], name='sales_preco_tabela__72c588_idx'), models.Index(fields=['produto'], name='sales_preco_produto_dea311_idx'), models.Index(fields=['tabela_codigo'], name='sales_preco_tabela__fb3be4_idx')],
                'unique_together': {('tabela_codigo', 'produto')},
            },
        ),
    ]
