# Generated by Django 5.2.8 on 2026-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0013_alinha_precoproduto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cores",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cor_id", models.PositiveIntegerField(db_index=True, unique=True, verbose_name="ID da Cor")),
                ("descricao", models.CharField(max_length=100, verbose_name="Descrição da Cor")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
        ),
    ]
