# Generated by Django 5.2.8 on 2026-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0014_cores"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormaPagamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("table_id", models.PositiveIntegerField(db_index=True, verbose_name="TableId (Ploomes)")),
                ("pagamento_id", models.PositiveIntegerField(db_index=True, verbose_name="ID da Forma de Pagamento")),
                ("descricao", models.CharField(max_length=150, verbose_name="Descrição")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Forma de Pagamento",
                "verbose_name_plural": "Formas de Pagamento",
                "ordering": ["descricao"],
                "unique_together": {("table_id", "pagamento_id")},
                "indexes": [models.Index(fields=["table_id", "pagamento_id"], name="sales_forma_table_i_3f3a6c_idx")],
            },
        ),
    ]
