# Generated by Django 4.2.15 on 2026-01-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_formapagamento'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='formapagamento',
            new_name='sales_forma_table_i_5d5889_idx',
            old_name='sales_forma_table_i_3f3a6c_idx',
        ),
    ]
