# Generated by Django 4.2.15 on 2026-01-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_rename_sales_forma_table_i_3f3a6c_idx_sales_forma_table_i_5d5889_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoinnovaro',
            name='freio',
            field=models.CharField(blank=True, choices=[('C', 'Com freio'), ('S', 'Sem freio')], max_length=10, verbose_name='Freio'),
        ),
        migrations.AddField(
            model_name='produtoinnovaro',
            name='mola',
            field=models.CharField(blank=True, choices=[('C', 'Com mola'), ('S', 'Sem mola')], max_length=10, verbose_name='Mola'),
        ),
    ]
