# Generated by Django 5.2.4 on 2026-01-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_produtoinnovaro_freio_produtoinnovaro_mola'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='observacao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
