# Generated by Django 4.2.15 on 2026-01-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_cartitem_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoinnovaro',
            name='modelo_simples',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo Simples'),
        ),
    ]
